---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-app-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wtistang/appsody_app
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: my-app-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/kabanero/appsody_app:tkn

