apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pipeline-run-pvc
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/lib/manual-pipeline-run-pvc

